### ISSUE TITLE
Using tunnels ?

### ISSUE THREAD

**Issue by naveenb29** [machzqcq/saucelabs#1]
What's a good way to specify a tunnel ? I trier using tunnelIdentifier but didn't seem to work. Is there an example someone can point me to ?
I get these error when I tried these keys
ArgumentError: unknown option: {:parentTunnel=>"sometunnel"}
ArgumentError: unknown option: {:tunnelIdentifier=>"sometunnel"}

**Comment by machzqcq** [comment]
Tunnel has to be installed on a machine and that acts as a conduit for traffic between your network and sauce network. Once you install a tunnel on the machine, lets say  <ip_address>, then in your conf, point to this machine i.e. change the GRID_URL to http://sauce_user:sauce_passwd@ip_address:4444/wd/hub" etc.

**Comment by naveenb29** [comment]
This was what I was looking for :+1: 

  @caps["parent-tunnel"] = 'scests'
